window.SCREENMATCH_DATA=[
/* APPLE — iPhone 11 through 18 */
{brand:"Apple",model:"iPhone 11",aliases:["iphone 11","11"],screen:[{model:"iPhone 11",level:"exact",label:"Exact",reason:"Designed for iPhone 11."},{model:"iPhone XR",level:"check",label:"Check fit",reason:"Same 6.1-inch class, but protector cutouts and edge coverage vary by product."}],camera:[{model:"iPhone 11",level:"exact",label:"Exact",reason:"Designed for the iPhone 11 dual-camera layout."}]},
{brand:"Apple",model:"iPhone 11 Pro",aliases:["iphone 11 pro","11 pro"],screen:[{model:"iPhone 11 Pro",level:"exact",label:"Exact",reason:"Designed for iPhone 11 Pro."},{model:"iPhone XS",level:"check",label:"Check fit",reason:"Same 5.8-inch display class, but verify the exact protector design."}],camera:[{model:"iPhone 11 Pro",level:"exact",label:"Exact",reason:"Designed for the iPhone 11 Pro triple-camera layout."}]},
{brand:"Apple",model:"iPhone 11 Pro Max",aliases:["iphone 11 pro max","11 pro max"],screen:[{model:"iPhone 11 Pro Max",level:"exact",label:"Exact",reason:"Designed for iPhone 11 Pro Max."},{model:"iPhone XS Max",level:"check",label:"Check fit",reason:"Same 6.5-inch display class, but verify the exact protector design."}],camera:[{model:"iPhone 11 Pro Max",level:"exact",label:"Exact",reason:"Designed for the iPhone 11 Pro Max triple-camera layout."}]},
{brand:"Apple",model:"iPhone 12 mini",aliases:["iphone 12 mini","12 mini"],screen:[{model:"iPhone 12 mini",level:"exact",label:"Exact",reason:"Designed for iPhone 12 mini."},{model:"iPhone 13 mini",level:"good",label:"Good match",reason:"12 mini and 13 mini share the same 5.4-inch form factor; verify the specific protector."}],camera:[{model:"iPhone 12 mini",level:"exact",label:"Exact",reason:"Designed for the iPhone 12 mini camera layout."},{model:"iPhone 13 mini",level:"check",label:"Check fit",reason:"Camera module details differ; use only a protector specifically listed for both."}]},
{brand:"Apple",model:"iPhone 12",aliases:["iphone 12","12"],screen:[{model:"iPhone 12",level:"exact",label:"Exact",reason:"Designed for iPhone 12."},{model:"iPhone 12 Pro",level:"good",label:"Good match",reason:"12 and 12 Pro share the same 6.1-inch front size; check the exact protector cutout."}],camera:[{model:"iPhone 12",level:"exact",label:"Exact",reason:"Designed for iPhone 12."},{model:"iPhone 11",level:"check",label:"Check fit",reason:"Some aftermarket camera protectors are sold for both, but the exact product design matters."}]},
{brand:"Apple",model:"iPhone 12 Pro",aliases:["iphone 12 pro","12 pro"],screen:[{model:"iPhone 12 Pro",level:"exact",label:"Exact",reason:"Designed for iPhone 12 Pro."},{model:"iPhone 12",level:"good",label:"Good match",reason:"12 and 12 Pro share the same 6.1-inch front size."}],camera:[{model:"iPhone 12 Pro",level:"exact",label:"Exact",reason:"Designed for the 12 Pro triple-camera layout."}]},
{brand:"Apple",model:"iPhone 12 Pro Max",aliases:["iphone 12 pro max","12 pro max"],screen:[{model:"iPhone 12 Pro Max",level:"exact",label:"Exact",reason:"Designed for iPhone 12 Pro Max."}],camera:[{model:"iPhone 12 Pro Max",level:"exact",label:"Exact",reason:"Designed for the 12 Pro Max triple-camera layout."}]},
{brand:"Apple",model:"iPhone 13 mini",aliases:["iphone 13 mini","13 mini"],screen:[{model:"iPhone 13 mini",level:"exact",label:"Exact",reason:"Designed for iPhone 13 mini."},{model:"iPhone 12 mini",level:"good",label:"Good match",reason:"12 mini and 13 mini share the same 5.4-inch form factor; verify the exact protector."}],camera:[{model:"iPhone 13 mini",level:"exact",label:"Exact",reason:"Designed for iPhone 13 mini."}]},
{brand:"Apple",model:"iPhone 13",aliases:["iphone 13","13"],screen:[{model:"iPhone 13",level:"exact",label:"Exact",reason:"Designed for iPhone 13."},{model:"iPhone 13 Pro",level:"good",label:"Good match",reason:"13 and 13 Pro share the same 6.1-inch front size; many protectors are sold for both."},{model:"iPhone 14",level:"check",label:"Check fit",reason:"Some aftermarket protectors are sold across the 13/13 Pro/14 family; verify the exact design."}],camera:[{model:"iPhone 13",level:"exact",label:"Exact",reason:"Designed for iPhone 13 dual-camera layout."}]},
{brand:"Apple",model:"iPhone 13 Pro",aliases:["iphone 13 pro","13 pro"],screen:[{model:"iPhone 13 Pro",level:"exact",label:"Exact",reason:"Designed for iPhone 13 Pro."},{model:"iPhone 13",level:"good",label:"Good match",reason:"13 and 13 Pro share the same 6.1-inch front size."},{model:"iPhone 14",level:"check",label:"Check fit",reason:"Some protectors are sold across this 6.1-inch family; verify cutouts and edge coverage."}],camera:[{model:"iPhone 13 Pro",level:"exact",label:"Exact",reason:"Designed for the 13 Pro triple-camera module."}]},
{brand:"Apple",model:"iPhone 13 Pro Max",aliases:["iphone 13 pro max","13 pro max"],screen:[{model:"iPhone 13 Pro Max",level:"exact",label:"Exact",reason:"Designed for iPhone 13 Pro Max."}],camera:[{model:"iPhone 13 Pro Max",level:"exact",label:"Exact",reason:"Designed for the 13 Pro Max triple-camera module."}]},
{brand:"Apple",model:"iPhone 14",aliases:["iphone 14","14"],screen:[{model:"iPhone 14",level:"exact",label:"Exact",reason:"Designed for iPhone 14."},{model:"iPhone 13",level:"check",label:"Check fit",reason:"Some aftermarket protectors are sold for 13/13 Pro/14; verify the exact product."},{model:"iPhone 13 Pro",level:"check",label:"Check fit",reason:"Some aftermarket protectors are sold for 13/13 Pro/14; verify the exact product."}],camera:[{model:"iPhone 14",level:"exact",label:"Exact",reason:"Designed for iPhone 14 camera layout."}]},
{brand:"Apple",model:"iPhone 14 Plus",aliases:["iphone 14 plus","14 plus"],screen:[{model:"iPhone 14 Plus",level:"exact",label:"Exact",reason:"Designed for iPhone 14 Plus."}],camera:[{model:"iPhone 14 Plus",level:"exact",label:"Exact",reason:"Designed for iPhone 14 Plus camera layout."}]},
{brand:"Apple",model:"iPhone 14 Pro",aliases:["iphone 14 pro","14 pro"],screen:[{model:"iPhone 14 Pro",level:"exact",label:"Exact",reason:"Designed for iPhone 14 Pro."}],camera:[{model:"iPhone 14 Pro",level:"exact",label:"Exact",reason:"Designed for the 14 Pro triple-camera module."}]},
{brand:"Apple",model:"iPhone 14 Pro Max",aliases:["iphone 14 pro max","14 pro max"],screen:[{model:"iPhone 14 Pro Max",level:"exact",label:"Exact",reason:"Designed for iPhone 14 Pro Max."}],camera:[{model:"iPhone 14 Pro Max",level:"exact",label:"Exact",reason:"Designed for the 14 Pro Max triple-camera module."}]},
{brand:"Apple",model:"iPhone 15",aliases:["iphone 15","15"],screen:[{model:"iPhone 15",level:"exact",label:"Exact",reason:"Designed for iPhone 15."}],camera:[{model:"iPhone 15",level:"exact",label:"Exact",reason:"Designed for iPhone 15 camera layout."}]},
{brand:"Apple",model:"iPhone 15 Plus",aliases:["iphone 15 plus","15 plus"],screen:[{model:"iPhone 15 Plus",level:"exact",label:"Exact",reason:"Designed for iPhone 15 Plus."}],camera:[{model:"iPhone 15 Plus",level:"exact",label:"Exact",reason:"Designed for iPhone 15 Plus camera layout."}]},
{brand:"Apple",model:"iPhone 15 Pro",aliases:["iphone 15 pro","15 pro"],screen:[{model:"iPhone 15 Pro",level:"exact",label:"Exact",reason:"Designed for iPhone 15 Pro."}],camera:[{model:"iPhone 15 Pro",level:"exact",label:"Exact",reason:"Designed for the 15 Pro camera layout."}]},
{brand:"Apple",model:"iPhone 15 Pro Max",aliases:["iphone 15 pro max","15 pro max"],screen:[{model:"iPhone 15 Pro Max",level:"exact",label:"Exact",reason:"Designed for iPhone 15 Pro Max."}],camera:[{model:"iPhone 15 Pro Max",level:"exact",label:"Exact",reason:"Designed for the 15 Pro Max camera layout."}]},
{brand:"Apple",model:"iPhone 16",aliases:["iphone 16","16"],screen:[{model:"iPhone 16",level:"exact",label:"Exact",reason:"Designed for iPhone 16."}],camera:[{model:"iPhone 16",level:"exact",label:"Exact",reason:"Designed for iPhone 16 camera layout."}]},
{brand:"Apple",model:"iPhone 16 Plus",aliases:["iphone 16 plus","16 plus"],screen:[{model:"iPhone 16 Plus",level:"exact",label:"Exact",reason:"Designed for iPhone 16 Plus."}],camera:[{model:"iPhone 16 Plus",level:"exact",label:"Exact",reason:"Designed for iPhone 16 Plus camera layout."}]},
{brand:"Apple",model:"iPhone 16e",aliases:["iphone 16e","16e"],screen:[{model:"iPhone 16e",level:"exact",label:"Exact",reason:"Designed for iPhone 16e."}],camera:[{model:"iPhone 16e",level:"exact",label:"Exact",reason:"Designed for the 16e camera layout."}]},
{brand:"Apple",model:"iPhone 16 Pro",aliases:["iphone 16 pro","16 pro"],screen:[{model:"iPhone 16 Pro",level:"exact",label:"Exact",reason:"Designed for iPhone 16 Pro."}],camera:[{model:"iPhone 16 Pro",level:"exact",label:"Exact",reason:"Designed for the 16 Pro camera layout."}]},
{brand:"Apple",model:"iPhone 16 Pro Max",aliases:["iphone 16 pro max","16 pro max"],screen:[{model:"iPhone 16 Pro Max",level:"exact",label:"Exact",reason:"Designed for iPhone 16 Pro Max."}],camera:[{model:"iPhone 16 Pro Max",level:"exact",label:"Exact",reason:"Designed for the 16 Pro Max camera layout."}]},
{brand:"Apple",model:"iPhone 17",aliases:["iphone 17","17"],screen:[{model:"iPhone 17",level:"exact",label:"Exact",reason:"Designed for iPhone 17."}],camera:[{model:"iPhone 17",level:"exact",label:"Exact",reason:"Designed for iPhone 17 camera layout."}]},
{brand:"Apple",model:"iPhone 17e",aliases:["iphone 17e","17e"],screen:[{model:"iPhone 17e",level:"exact",label:"Exact",reason:"Designed for iPhone 17e."}],camera:[{model:"iPhone 17e",level:"exact",label:"Exact",reason:"Designed for iPhone 17e."}]},
{brand:"Apple",model:"iPhone 17 Air",aliases:["iphone 17 air","iphone air","17 air","air"],screen:[{model:"iPhone 17 Air",level:"exact",label:"Exact",reason:"Designed for iPhone Air."}],camera:[{model:"iPhone 17 Air",level:"exact",label:"Exact",reason:"Designed for iPhone Air camera layout."}]},
{brand:"Apple",model:"iPhone 17 Pro",aliases:["iphone 17 pro","17 pro"],screen:[{model:"iPhone 17 Pro",level:"exact",label:"Exact",reason:"Designed for iPhone 17 Pro."}],camera:[{model:"iPhone 17 Pro",level:"exact",label:"Exact",reason:"Designed for the 17 Pro camera layout."}]},
{brand:"Apple",model:"iPhone 17 Pro Max",aliases:["iphone 17 pro max","17 pro max"],screen:[{model:"iPhone 17 Pro Max",level:"exact",label:"Exact",reason:"Designed for iPhone 17 Pro Max."}],camera:[{model:"iPhone 17 Pro Max",level:"exact",label:"Exact",reason:"Designed for the 17 Pro Max camera layout."}]},
{brand:"Apple",model:"iPhone 18 Pro",aliases:["iphone 18 pro","18 pro"],screen:[{model:"iPhone 18 Pro",level:"exact",label:"Exact",reason:"Designed for iPhone 18 Pro."}],camera:[{model:"iPhone 18 Pro",level:"exact",label:"Exact",reason:"Designed for the 18 Pro camera layout."}]},
{brand:"Apple",model:"iPhone 18 Pro Max",aliases:["iphone 18 pro max","18 pro max"],screen:[{model:"iPhone 18 Pro Max",level:"exact",label:"Exact",reason:"Designed for iPhone 18 Pro Max."}],camera:[{model:"iPhone 18 Pro Max",level:"exact",label:"Exact",reason:"Designed for the 18 Pro Max camera layout."}]},

/* SAMSUNG GALAXY A SERIES — A06 and newer/current families */
{brand:"Samsung",model:"Galaxy A06",aliases:["a06","galaxy a06","samsung a06"],screen:[{model:"Galaxy A06",level:"exact",label:"Exact",reason:"Designed for Galaxy A06."}],camera:[{model:"Galaxy A06",level:"exact",label:"Exact",reason:"Designed for Galaxy A06 camera layout."}]},
{brand:"Samsung",model:"Galaxy A06 5G",aliases:["a06 5g","galaxy a06 5g"],screen:[{model:"Galaxy A06 5G",level:"exact",label:"Exact",reason:"Designed for Galaxy A06 5G."}],camera:[{model:"Galaxy A06 5G",level:"exact",label:"Exact",reason:"Designed for Galaxy A06 5G camera layout."}]},
{brand:"Samsung",model:"Galaxy A15 / A15 5G",aliases:["a15","a15 5g","galaxy a15","galaxy a15 5g"],screen:[{model:"Galaxy A15 / A15 5G",level:"exact",label:"Exact",reason:"Use protectors explicitly listed for A15/A15 5G."}],camera:[{model:"Galaxy A15 / A15 5G",level:"exact",label:"Exact",reason:"Use a protector designed for the A15/A15 5G camera layout."}]},
{brand:"Samsung",model:"Galaxy A16 / A16 5G",aliases:["a16","a16 5g","galaxy a16","galaxy a16 5g"],screen:[{model:"Galaxy A16 / A16 5G",level:"exact",label:"Exact",reason:"Use protectors explicitly listed for A16/A16 5G."}],camera:[{model:"Galaxy A16 / A16 5G",level:"exact",label:"Exact",reason:"Use a protector designed for the A16/A16 5G camera layout."}]},
{brand:"Samsung",model:"Galaxy A17 5G",aliases:["a17","a17 5g","galaxy a17","galaxy a17 5g"],screen:[{model:"Galaxy A17 5G",level:"exact",label:"Exact",reason:"Designed for Galaxy A17 5G."}],camera:[{model:"Galaxy A17 5G",level:"exact",label:"Exact",reason:"Designed for Galaxy A17 5G camera layout."}]},
{brand:"Samsung",model:"Galaxy A25 5G",aliases:["a25","a25 5g","galaxy a25"],screen:[{model:"Galaxy A25 5G",level:"exact",label:"Exact",reason:"Designed for Galaxy A25 5G."}],camera:[{model:"Galaxy A25 5G",level:"exact",label:"Exact",reason:"Designed for Galaxy A25 5G camera layout."}]},
{brand:"Samsung",model:"Galaxy A26 5G",aliases:["a26","a26 5g","galaxy a26"],screen:[{model:"Galaxy A26 5G",level:"exact",label:"Exact",reason:"Designed for Galaxy A26 5G."}],camera:[{model:"Galaxy A26 5G",level:"exact",label:"Exact",reason:"Designed for Galaxy A26 5G camera layout."}]},
{brand:"Samsung",model:"Galaxy A27 5G",aliases:["a27","a27 5g","galaxy a27"],screen:[{model:"Galaxy A27 5G",level:"exact",label:"Exact",reason:"Designed for Galaxy A27 5G."}],camera:[{model:"Galaxy A27 5G",level:"exact",label:"Exact",reason:"Designed for Galaxy A27 5G camera layout."}]},
{brand:"Samsung",model:"Galaxy A34 5G",aliases:["a34","a34 5g","galaxy a34"],screen:[{model:"Galaxy A34 5G",level:"exact",label:"Exact",reason:"Designed for Galaxy A34 5G."}],camera:[{model:"Galaxy A34 5G",level:"exact",label:"Exact",reason:"Designed for Galaxy A34 5G camera layout."}]},
{brand:"Samsung",model:"Galaxy A35 5G",aliases:["a35","a35 5g","galaxy a35"],screen:[{model:"Galaxy A35 5G",level:"exact",label:"Exact",reason:"Designed for Galaxy A35 5G."}],camera:[{model:"Galaxy A35 5G",level:"exact",label:"Exact",reason:"Designed for Galaxy A35 5G camera layout."}]},
{brand:"Samsung",model:"Galaxy A36 5G",aliases:["a36","a36 5g","galaxy a36"],screen:[{model:"Galaxy A36 5G",level:"exact",label:"Exact",reason:"Designed for Galaxy A36 5G."}],camera:[{model:"Galaxy A36 5G",level:"exact",label:"Exact",reason:"Designed for Galaxy A36 5G camera layout."}]},
{brand:"Samsung",model:"Galaxy A37 5G",aliases:["a37","a37 5g","galaxy a37"],screen:[{model:"Galaxy A37 5G",level:"exact",label:"Exact",reason:"Designed for Galaxy A37 5G."}],camera:[{model:"Galaxy A37 5G",level:"exact",label:"Exact",reason:"Designed for Galaxy A37 5G camera layout."}]},
{brand:"Samsung",model:"Galaxy A52",aliases:["a52","galaxy a52"],screen:[{model:"Galaxy A52",level:"exact",label:"Exact",reason:"Designed for Galaxy A52."},{model:"Galaxy A52 5G",level:"good",label:"Good match",reason:"A52 and A52 5G share the same front display dimensions; verify the exact protector."}],camera:[{model:"Galaxy A52",level:"exact",label:"Exact",reason:"Designed for Galaxy A52 camera layout."}]},
{brand:"Samsung",model:"Galaxy A52 5G",aliases:["a52 5g","galaxy a52 5g"],screen:[{model:"Galaxy A52 5G",level:"exact",label:"Exact",reason:"Designed for Galaxy A52 5G."},{model:"Galaxy A52",level:"good",label:"Good match",reason:"A52 and A52 5G share the same front display dimensions; verify the exact protector."}],camera:[{model:"Galaxy A52 5G",level:"exact",label:"Exact",reason:"Designed for Galaxy A52 5G camera layout."}]},
{brand:"Samsung",model:"Galaxy A52s 5G",aliases:["a52s","a52s 5g","galaxy a52s"],screen:[{model:"Galaxy A52s 5G",level:"exact",label:"Exact",reason:"Designed for Galaxy A52s 5G."},{model:"Galaxy A52 / A52 5G",level:"good",label:"Good match",reason:"The A52 family shares the same front dimensions; verify the exact protector."}],camera:[{model:"Galaxy A52s 5G",level:"exact",label:"Exact",reason:"Designed for Galaxy A52s 5G camera layout."}]},
{brand:"Samsung",model:"Galaxy A53 5G",aliases:["a53","a53 5g","galaxy a53"],screen:[{model:"Galaxy A53 5G",level:"exact",label:"Exact",reason:"Designed for Galaxy A53 5G."},{model:"Galaxy A52 / A52 5G / A52s 5G",level:"check",label:"Check fit",reason:"Some accessory makers group these models, but verify the exact protector and edge coverage."}],camera:[{model:"Galaxy A53 5G",level:"exact",label:"Exact",reason:"Designed for Galaxy A53 5G camera layout."}]},
{brand:"Samsung",model:"Galaxy A54 5G",aliases:["a54","a54 5g","galaxy a54"],screen:[{model:"Galaxy A54 5G",level:"exact",label:"Exact",reason:"Designed for Galaxy A54 5G."}],camera:[{model:"Galaxy A54 5G",level:"exact",label:"Exact",reason:"Designed for Galaxy A54 5G camera layout."}]},
{brand:"Samsung",model:"Galaxy A55 5G",aliases:["a55","a55 5g","galaxy a55"],screen:[{model:"Galaxy A55 5G",level:"exact",label:"Exact",reason:"Designed for Galaxy A55 5G."}],camera:[{model:"Galaxy A55 5G",level:"exact",label:"Exact",reason:"Designed for Galaxy A55 5G camera layout."}]},
{brand:"Samsung",model:"Galaxy A56 5G",aliases:["a56","a56 5g","galaxy a56"],screen:[{model:"Galaxy A56 5G",level:"exact",label:"Exact",reason:"Designed for Galaxy A56 5G."}],camera:[{model:"Galaxy A56 5G",level:"exact",label:"Exact",reason:"Designed for Galaxy A56 5G camera layout."}]},
{brand:"Samsung",model:"Galaxy A57 5G",aliases:["a57","a57 5g","galaxy a57"],screen:[{model:"Galaxy A57 5G",level:"exact",label:"Exact",reason:"Designed for Galaxy A57 5G."}],camera:[{model:"Galaxy A57 5G",level:"exact",label:"Exact",reason:"Designed for Galaxy A57 5G camera layout."}]},
{brand:"Samsung",model:"Galaxy A70",aliases:["a70","samsung a70","galaxy a70"],screen:[{model:"Galaxy A70",level:"exact",label:"Exact",reason:"Designed for Galaxy A70."}],camera:[{model:"Galaxy A70",level:"exact",label:"Exact",reason:"Designed for Galaxy A70."}]},
{brand:"Samsung",model:"Galaxy A71 5G",aliases:["a71","a71 5g","galaxy a71"],screen:[{model:"Galaxy A71 5G",level:"exact",label:"Exact",reason:"Designed for Galaxy A71 5G."}],camera:[{model:"Galaxy A71 5G",level:"exact",label:"Exact",reason:"Designed for Galaxy A71 5G camera layout."}]},
{brand:"Samsung",model:"Galaxy A72",aliases:["a72","galaxy a72"],screen:[{model:"Galaxy A72",level:"exact",label:"Exact",reason:"Designed for Galaxy A72."}],camera:[{model:"Galaxy A72",level:"exact",label:"Exact",reason:"Designed for Galaxy A72 camera layout."}]},
{brand:"Samsung",model:"Galaxy A73 5G",aliases:["a73","a73 5g","galaxy a73"],screen:[{model:"Galaxy A73 5G",level:"exact",label:"Exact",reason:"Designed for Galaxy A73 5G."}],camera:[{model:"Galaxy A73 5G",level:"exact",label:"Exact",reason:"Designed for Galaxy A73 5G camera layout."}]}
];

/* PHONE CASE COMPATIBILITY — conservative by design.
   Only groups supported by matching dimensions/cutouts or manufacturer listings are marked compatible.
   All other models default to Exact only until verified. */
(()=>{
 const groups=[
  {models:["iPhone 12","iPhone 12 Pro"],level:"good",reason:"These two phones have identical body dimensions and cases are commonly sold for both; camera openings should still be checked."},
  {models:["Galaxy A15 / A15 5G"],level:"good",reason:"A15 and A15 5G cases are commonly listed together and the external dimensions/port layout match."},
  {models:["Galaxy A52","Galaxy A52 5G","Galaxy A52s 5G"],level:"good",reason:"These A52 variants share the same external dimensions and case/cutout layout."}
 ];
 const byModel=new Map();
 groups.forEach(g=>g.models.forEach(m=>byModel.set(m,g)));
 window.SCREENMATCH_DATA.forEach(item=>{
   const g=byModel.get(item.model);
   const exact={model:item.model,level:"exact",label:"Exact",reason:"Designed/listed for this exact phone model."};
   if(g){
     item.case=[exact,...g.models.filter(m=>m!==item.model).map(m=>({model:m,level:g.level,label:"Good match",reason:g.reason}))];
   }else{
     item.case=[exact];
   }
 });
})();